require: rubocop-rspec
inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
AllCops:
  TargetRubyVersion: 2.6.5
FactoryBot/AttributeDefinedStatically:
  Enabled: true
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
