version: '3'
services:
  app:
    build: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    env_file: .env
    environment:
      TZ: Asia/Tokyo
    stdin_open: true
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - bundler-store:/usr/local/bundle
    depends_on:
      - db
      - cache
      - worker

  worker:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml -e development
    env_file: .env
    environment:
      TZ: Asia/Tokyo
    stdin_open: true
    volumes:
      - .:/app
      - bundler-store:/usr/local/bundle
    depends_on:
      - db
      - cache

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 4306:3306
    volumes:
      - ./docker-compose/mysql:/etc/mysql/conf.d
      - mysql-store:/var/lib/mysql

  cache:
    image: redis:5
    environment:
      TZ: Asia/Tokyo
    ports:
      - 6380:6379

volumes:
  mysql-store:
  bundler-store:
