source 'https://rubygems.org'
gem 'rails', '4.0.13'
gem 'mysql2', '~> 0.3.0'
gem 'unicorn'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'jpmobile', '~> 4.0.0'
gem 'detect_timezone_rails'
gem 'configatron'
gem 'twitter'
gem 'omniauth'
gem 'omniauth-twitter', github: 'arunagw/omniauth-twitter'
gem 'twitter-text'
gem 'turnout'
