# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "capistrano"
gem "capistrano-rbenv"
gem "capistrano-bundler"
gem "capistrano-rails"
gem "capistrano3-puma"
gem "capistrano-sidekiq"
