production:
    site_name: Timedline
    site_url: http://timedline.me
    site_mode: production
    consumer_key: 
    consumer_secret: 
    admin_users : "704706890"

development:
    site_name: Timedline
    site_url: http://localhost:3000/
    site_mode: development
    consumer_key: 
    consumer_secret: 
    admin_users : "704706890"

test:
    site_name: Timedline
    site_url: http://localhost:3000/
    site_mode: test
    consumer_key: 
    consumer_secret: 
    admin_users : "704706890"