production:
    site_name: SITE_NAME
    site_url: http://SITE_URL
    site_mode: production
    consumer_key:
    consumer_secret:
    access_token:
    access_token_secret:
    admin_users :
    service_owner_twitter_id :

development:
    site_name: SITE_NAME
    site_url: http://localhost:3000/
    site_mode: development
    consumer_key:
    consumer_secret:
    access_token:
    access_token_secret:
    admin_users :
    service_owner_twitter_id :

test:
    site_name: SITE_NAME
    site_url: http://localhost:3000/
    site_mode: test
    consumer_key:
    consumer_secret:
    access_token:
    access_token_secret:
    admin_users :
    service_owner_twitter_id :