base: &base
  adapter: mysql2
  database: some_database
  username: 
  password: 
  host: 
  encoding: utf8

development:
  <<: *base
  database: 

development:
  <<: *base
  database: 

development:
  <<: *base
  database: 