base: &base
  adapter: mysql2
  database:
  username:
  password:
  host:
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4

development:
  <<: *base
  database:

test:
  <<: *base
  database:

production:
  <<: *base
  database:
