development:
  adapter: mysql2
  database: timedline_rails
  username: root
  password:
  host: 127.0.0.1
  encoding: utf8

test:
  adapter: mysql2
  database: testtimedline_rails
  username: root
  password:
  host: 127.0.0.1
  encoding: utf8

production:
  adapter: mysql2
  database: timedline_rails
  username: root
  password:
  host: 127.0.0.1
  encoding: utf8