development:
  adapter: mysql2
  database: 
  username: 
  password: 
  host: 
  encoding: utf8

test:
  adapter: mysql2
  database: 
  username: 
  password: 
  host: 
  encoding: utf8

production:
  adapter: mysql2
  database: 
  username: 
  password: 
  host: 
  encoding: utf8
