base: &base
  adapter: mysql2
  username: <%= ENV.fetch('JUMP_DB_USER_NAME') %>
  password: <%= ENV.fetch('JUMP_DB_PASSWORD') %>
  host: <%= ENV.fetch('JUMP_DB_HOST') %>
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4

development:
  <<: *base
  database: jump_development

test:
  <<: *base
  database: jump_test

staging:
  <<: *base
  database: jump_staging

production:
  <<: *base
  database: <%= ENV['JUMP_DB_NAME'] %>
