redis:
  namespace: <%= [Rails.application.class.module_parent_name, Rails.env].join(":") %>
  endpoint:  redis://<%= ENV.fetch("JUMP_CACHE_HOST") %>:<%= ENV.fetch("JUMP_CACHE_PORT") %>/0

sidekiq:
  namespace: <%= [Rails.application.class.module_parent_name, Rails.env, "sidekiq"].join(":") %>

twitter:
  consumer_key: <%= ENV.fetch('TWITTER_CONSUMER_KEY') %>
  consumer_secret: <%= ENV.fetch('TWITTER_CONSUMER_SECRET') %>
  traceable_tweet_count_limit: 3200

frontend_url: https://<%= ENV.fetch('FRONTEND_HOST') %>
frontend_host: <%= ENV.fetch('FRONTEND_HOST') %>
authorized_host: <%= ENV.fetch('AUTHORIZED_HOST') %>

set_cookie_domain: all

admin_user_twitter_id: <%= ENV.fetch("ADMIN_USER_TWITTER_ID") %>

slow_query_threshold: <%= ENV.fetch("SLOW_QUERY_THRESHOLD", 1.0) %>

sitemap_dir: "frontend/build"
