site_name: <%= ENV.fetch('SITE_NAME') %>

redis:
  namespace: <%= [Rails.application.class.module_parent_name, Rails.env].join(":") %>
  endpoint:  redis://<%= ENV.fetch("JUMP_CACHE_HOST") %>:<%= ENV.fetch("JUMP_CACHE_PORT") %>/0

sidekiq:
  namespace: <%= [Rails.application.class.module_parent_name, Rails.env, "sidekiq"].join(":") %>

twitter:
  consumer_key: <%= ENV.fetch('TWITTER_CONSUMER_KEY') %>
  consumer_secret: <%= ENV.fetch('TWITTER_CONSUMER_SECRET') %>
  traceable_tweet_count_limit: 3200

sidekiq_dashboard_user_id: <%= ENV.fetch('SIDEKIQ_DASHBOARD_USER_ID') %>
