site_name: <%= ENV.fetch('SITE_NAME') %>

twitter:
  consumer_key: <%= ENV.fetch('TWITTER_CONSUMER_KEY') %>
  consumer_secret: <%= ENV.fetch('TWITTER_CONSUMER_SECRET') %>
  traceable_tweet_count_limit: 3200

sidekiq_dashboard_user_id: <%= ENV.fetch('SIDEKIQ_DASHBOARD_USER_ID') %>
