site_name: <%= ENV.fetch('SITE_NAME') %>

twitter:
  consumer_key: <%= ENV.fetch('TWITTER_CONSUMER_KEY') %>
  consumer_secret: <%= ENV.fetch('TWITTER_CONSUMER_SECRET_KEY') %>

sidekiq_dashboard_user_id: <%= ENV.fetch('SIDEKIQ_DASHBOARD_USER_ID') %>
