development:
  worker_num: 1
  socket_path: "unix:tmp/unicorn/development.sock"
  pid_path: "tmp/unicorn/development.pid"

production:
  worker_num: 3
  socket_path: "unix:tmp/unicorn/production.sock"
  pid_path: "tmp/unicorn/production.pid"
