base: &base
  socket_path: "unix:tmp/unicorn.sock"
  pid_path:    "tmp/unicorn.pid"

development:
  <<: *base
  worker_num: 1
  socket_path: "unix:tmp/unicorn_development.sock"
  pid_path:    "tmp/unicorn_development.pid"

production:
  <<: *base
  worker_num: 3
  socket_path: "unix:tmp/unicorn_production.sock"
  pid_path:    "tmp/unicorn_production.pid"