name: Frontend
on:
  push:
    paths:
    - 'frontend/**'
    - '.github/workflows/frontend.yml'

env:
  REACT_APP_SERVICE_NAME: test
  REACT_APP_SERVICE_DOMAIN: localhost
  REACT_APP_META_DESCRIPTION: foo
  REACT_APP_OG_TITLE: bar
  REACT_APP_API_ORIGIN: http://localhost:3000
  REACT_APP_AUTH_ORIGIN: http://localhost:3000
  REACT_APP_SITE_HOST_URL: http://foo.com
  REACT_APP_SENTRY_DSN: https://123@sentry.io/123456
  REACT_APP_ANALYTICS_ID: foo
  REACT_APP_AD_ID: foo
  REACT_APP_AD_SLOT_ABOVE_TWEETS: 111
  REACT_APP_AD_SLOT_TOP: 111
  REACT_APP_HIDE_AD: true
  REACT_APP_ADMIN_TWITTER_SCREEN_NAME: foo

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/frontend/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: Lint
      working-directory: frontend
      run: |
        yarn install
        yarn lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/frontend/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: Run tests
      working-directory: frontend
      run: |
        yarn install
        yarn test:ci

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/frontend/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: Build
      working-directory: frontend
      run: |
        yarn install --production
        yarn build
